---
services:
   checkmk:
     image: checkmk/check-mk-raw:2.4.0p10
     container_name: checkmk
     hostname: checkmk
     restart: "unless-stopped"
     ports:
       #- "162:162/udp"
       #- "514:514/udp"
       #- "514:514/tcp"
       #- "6557:6557/tcp"
       - "9090:9090/tcp"
       - "8000:8000"
     environment:
       - MAIL_RELAY_HOST=mailrelay.example.com
       - CMK_SITE_ID=cmk
       - CMK_PASSWORD=password
       - CMK_LIVESTATUS_TCP=on
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - cmkvol:/omd/sites
     networks:
       - backend
volumes:
  cmkvol:
networks:
  backend:
    name: nautobot_backend
    driver: bridge
